name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build - zenith-lexer
      working-directory: ./zenith-lexer
      run: cargo build --verbose
    - name: Run tests - zenith-lexer
      working-directory: ./zenith-lexer
      run: cargo test --verbose
    - name: Run Clippy - zenith-lexer
      working-directory: ./zenith-lexer
      run: cargo clippy
